kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-app-pv-volume
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce