apiVersion: v1
kind: Service
metadata:
  name: jenkins-x
  namespace: jcasc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jenkins-x

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-x-jnlp
  namespace: jcasc
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins-x