apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jcasc
  labels:
    app: jenkins
spec:
  ports:
  - port: 80
    name: ui
    protocol: TCP
    targetPort: 8080
  - port: 50000
    name: agents
    protocol: TCP
    targetPort: 50000
  type: NodePort
  selector:
    app: jenkins
